### ISSUE TITLE
'ModbusSingleRequestHandler' object is not callable

### ISSUE THREAD

**Issue by Radu-0** [riptideio/pymodbus#1159]
### Versions

* Python: 3.11
* OS: Windows 10
* Pymodbus: 3.0.0 (from pip)
* Modbus Hardware (if used):

### Pymodbus Specific
* Server: RTU - sync/async
* Client: tcp/rtu/ascii - sync/async

### Description
Trying to start a SerialServer but I get the above error
Looks like the handler set up in ModbusSerialServer constructor(async_io.py #line 811)  is not callable 

### Code and Logs
Starting the server:
StartSerialServer(context=context, port='COM4', baudrate=9600, stopbits=1, bytesize=8, framer=ModbusRtuFramer)
```python
# code and logs here.
Traceback (most recent call last):
  File "C:\Users\R\AppData\Roaming\Python\Python311\site-packages\pymodbus\server\async_io.py", line 844, in _connect
    self.transport, self.protocol = await create_serial_connection(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\R\AppData\Roaming\Python\Python311\site-packages\serial_asyncio\__init__.py", line 449, in create_serial_connection
    transport, protocol = await connection_for_serial(loop, protocol_factory, serial_instance)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\R\AppData\Roaming\Python\Python311\site-packages\serial_asyncio\__init__.py", line 476, in connection_for_serial
    protocol = protocol_factory()
               ^^^^^^^^^^^^^^^^^^
TypeError: 'ModbusSingleRequestHandler' object is not callable

# please use the following to format logs when posting them here
import pymodbus
pymodbus.pymodbus_apply_logging_config()
```

**Comment by janiversen** [comment]
This is a known bug, solved on dev. It will be part of the upcoming v3.0.1 (due within a week).
