### ISSUE TITLE
Writing booleans on async server results in struct.unpack error

### ISSUE THREAD

**Issue by muldereric** [riptideio/pymodbus#128]
Config that I am using (stripped down version):

```
def main():
    store = ModbusSlaveContext(
        blk1 = ModbusSequentialDataBlock(0x000, [0] * 1),
        blk2 = ModbusSequentialDataBlock(0x00B, [0] * 1),
        blk3 = ModbusSequentialDataBlock(0x032, [0] * 4),
        blk4 = ModbusSequentialDataBlock(0x066, [0] * 34),
        blk5 = ModbusSequentialDataBlock(0x088, [0] * 34),
        blk6 = ModbusSequentialDataBlock(0x0AA, [0] * 34),
        blk7 = ModbusSequentialDataBlock(0x0CC, [0] * 14),
        blk8 = ModbusSequentialDataBlock(0x3E8, [0] * 5),
        blk9 = ModbusSequentialDataBlock(0xDAC, [0] * 4))
    context= ModbusServerContext(slaves=store, single=True)

    identity= ModbusDeviceIdentification()
    identity.VendorName  = 'My Name'
    identity.ProductCode = 'Simulator'
    identity.VendorUrl   = 'http://mydomain.net'
    identity.ProductName = 'Raspberry Pi 3 Modbus TCP Server'
    identity.ModelName   = 'Raspberry Pi 3 Modbus TCP Server'
    identity.MajorMinorRevision = '1.0'

    try:
        loop = LoopingCall(f=update_values, a=(context, ))
        loop.start(30, now=False)
        StartTcpServer(context, identity=identity)
    except KeyboardInterrupt:
        loop.stop()
```

When a boolean is written to the server, the following error occurs:

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/local/lib/python2.7/dist-packages/pymodbus/server/async.py", line 59, in dataReceived
    self.framer.processIncomingPacket(data, self._execute)
  File "/usr/local/lib/python2.7/dist-packages/pymodbus/transaction.py", line 349, in processIncomingPacket
    result = self.decoder.decode(self.getFrame())
  File "/usr/local/lib/python2.7/dist-packages/pymodbus/factory.py", line 106, in decode
    return self._helper(message)
  File "/usr/local/lib/python2.7/dist-packages/pymodbus/factory.py", line 133, in _helper
    request.decode(data[1:])
  File "/usr/local/lib/python2.7/dist-packages/pymodbus/bit_write_message.py", line 68, in decode
    self.address, value = struct.unpack('>HH', data)
struct.error: unpack requires a string argument of length 4
```

Because I am not that familliar with Python or the pymodbus library yet, this issue may just be a programming error, but as far as I can tell, there's nothing wrong with my code.
As long as I don't let my Modbus TCP Client write to the booleans, this script runs fine. When I write to a boolean from the client, the script comes up with the error mentioned above and doesn't drop it anymore.. It keeps coming back everytime the LoopingCall callback function is executed.

**Comment by muldereric** [comment]
Does anyone have an idea on what is going wrong here? 
I'm not a Python guru and just know some basics, but would love to get this one solved with some help.

**Comment by muldereric** [comment]
Figured out that the error is caused by the client writing data to the server.
When I use Kepware to simulate my client, everything works as expected, however the other software package does not use/send the CRC byte

**Comment by dhoomakethu** [comment]
Pymodbus need complete packet (with CRC) to decode a request, I will close this issue as this is not related to pymodbus.
