### ISSUE TITLE
Python 3.5: One test case fails

### ISSUE THREAD

**Issue by MartinBorg** [riptideio/pymodbus#166]
When trying to build a Debian package from pymodbus 1.3.0~rc1, I get:
```
   dh_auto_test -O--buildsystem=pybuild
I: pybuild base:184: cd '/build/pymodbus-1.3.0~rc1/.pybuild/pythonX.Y_2.7/build'; python2.7 -m nose test
.....................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 261 tests in 0.568s

OK
I: pybuild base:184: cd '/build/pymodbus-1.3.0~rc1/.pybuild/pythonX.Y_3.5/build'; python3.5 -m nose test
.....................................................................................................................................................E...............................................................................................................
======================================================================
ERROR: Test that the read fifo queue response can encode
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/pymodbus-1.3.0~rc1/.pybuild/pythonX.Y_3.5/build/test/test_mei_messages.py", line 80, in testReadDeviceInformationResponseEncode
    result  = handle.encode()
  File "/build/pymodbus-1.3.0~rc1/.pybuild/pythonX.Y_3.5/build/pymodbus/mei_message.py", line 135, in encode
    packet += data.encode()
AttributeError: 'bytes' object has no attribute 'encode'

----------------------------------------------------------------------
Ran 261 tests in 0.539s

FAILED (errors=1)
E: pybuild pybuild:283: test: plugin distutils failed with: exit code=1: cd '/build/pymodbus-1.3.0~rc1/.pybuild/pythonX.Y_3.5/build'; python3.5 -m nose test
```

**Comment by dhoomakethu** [comment]
will be fixed with PR #168
