### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by dmdelorme** [riptideio/pymodbus#238]
<!--

### Versions

* Python: 2.7
* OS:Linux openplotter 4.9.13-v7+ #974 SMP Wed Mar 1 20:09:48 GMT 2017 armv7l GNU/Linux
* Pymodbus: current  pymodbus==1.3.2
* Modbus Hardware (if used):  epsolar tracer A

### Description
every second time i run the following code i/rpi3 has issues

### Code and Logs
```
import logging
logging.basicConfig()
log = logging.getLogger()
log.setLevel(logging.DEBUG)
from pymodbus.client.sync import ModbusSerialClient as ModbusClient
#from pymodbus.mei_message import *
import socket
client = ModbusClient(method='rtu', port='/dev/ttyXRUSB0', baudrate=115200, stopbits = 1, bytesize = 8, timeout = 1)
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
client.connect()
#request = ReadDeviceInformationRequest(unit=1)
#response = client.execute(request)
#print repr(response.information)

result = client.read_input_registers(0x3100,10,unit=1)
pvVolts = float(result.registers[0] / 100.0)
pvAmps = float(result.registers[1] / 100.0)
batVolts = float(result.registers[4] / 100.0)
batchgAmps = float(result.registers[5] / 100.0)
ldVolts = float(result.registers[8] / 100.00)
ldAmps = float(result.registers[9] / 100.00)
ldnetAmps = batchgAmps-ldAmps
result2 = client.read_input_registers(0x3110,1,unit=1)
batTemp = float((result2.registers[0] / 100)+ 273.15)
#print 'send'
SignalK = '{"updates": [{"source": {"type": "CHARGER","src" : "epsolar"},"values":['
SignalK += '{"path": "electrical.chargers.tracer.batteries.main.voltage","value":'+str(round(batVolts, 2))+'}'
SignalK += ',{"path": "electrical.chargers.tracer.batteries.charge.current","value":'+str(batchgAmps)+'}'
SignalK += ',{"path": "electrical.chargers.tracer.pv.voltage","value":'+str(round(pvVolts,2))+'}'
SignalK += ',{"path": "electrical.chargers.tracer.pv.current","value":'+str(pvAmps)+'}'
SignalK += ',{"path": "electrical.chargers.tracer.load.voltage","value":'+str(ldVolts)+'}'
SignalK += ',{"path": "electrical.chargers.tracer.load.current","value":'+str(ldAmps)+'}'
SignalK += ',{"path": "electrical.chargers.tracer.loadnet.current","value":'+str(ldnetAmps)+'}'
SignalK += ',{"path": "electrical.chargers.tracer.batteries.temp","value":'+str(batTemp)+'}'
SignalK += ']}]}\n'
sock.sendto(SignalK, ('localhost', 55559))
#print pvVolts
#print pvAmps
#print result2.registers[0]/100
#print batteryAmps
print batTemp
client.close()
```
debug output
```
 python sktest.py 
DEBUG:pymodbus.transaction:Running transaction 1
DEBUG:pymodbus.transaction:send: 0x1 0x4 0x31 0x0 0x0 0xa 0x7e 0xf1
DEBUG:pymodbus.client.sync:will sleep to wait for 3.5 char
DEBUG:pymodbus.transaction:recv: 0x1 0x4 0x14 0x0 0x5a 0x0 0x0
DEBUG:pymodbus.factory:Factory Response[1]
DEBUG:pymodbus.transaction:Transaction failed. (Modbus Error: [Invalid Message] ReadBitResponse(40)) 
DEBUG:pymodbus.transaction:send: 0x1 0x4 0x31 0x0 0x0 0xa 0x7e 0xf1
DEBUG:pymodbus.client.sync:will sleep to wait for 3.5 char
DEBUG:pymodbus.transaction:recv: 0x1 0x4 0x14 0x0 0x4f 0x0 0x0 0x0 0x0 0x0 0x0 0x4 0xe6 0x0 0x0 0x0 0x0 0x0 0x0 0x4 0xe6 0x0 0x1f 0xce 0xd0
DEBUG:pymodbus.factory:Factory Response[1]
DEBUG:pymodbus.transaction:Transaction failed. (Modbus Error: [Invalid Message] ReadBitResponse(240)) 
DEBUG:pymodbus.transaction:send: 0x1 0x4 0x31 0x0 0x0 0xa 0x7e 0xf1
DEBUG:pymodbus.client.sync:will sleep to wait for 3.5 char
DEBUG:pymodbus.transaction:recv: 0x1 0x4 0x14 0x0 0x52 0x0 0x0 0x0 0x0 0x0 0x0 0x4 0xe7 0x0 0x0 0x0 0x0 0x0 0x0 0x4 0xe7 0x0 0x1b 0x70 0x41
DEBUG:pymodbus.factory:Factory Response[1]
DEBUG:pymodbus.transaction:Transaction failed. (Modbus Error: [Invalid Message] ReadBitResponse(440)) 
DEBUG:pymodbus.transaction:getting transaction 1
Traceback (most recent call last):
  File "sktest.py", line 16, in <module>
    pvVolts = float(result.registers[0] / 100.0)
AttributeError: 'ModbusIOException' object has no attribute 'registers'
pi@openplotter:~/testepsolar $ python sktest.py 
DEBUG:pymodbus.transaction:Running transaction 1
DEBUG:pymodbus.transaction:send: 0x1 0x4 0x31 0x0 0x0 0xa 0x7e 0xf1
DEBUG:pymodbus.client.sync:will sleep to wait for 3.5 char
DEBUG:pymodbus.transaction:recv: 0x1 0x4 0x14 0x0 0x5d 0x0 0x0 0x0 0x0 0x0 0x0 0x4 0xe7 0x0 0x0 0x0 0x0 0x0 0x0 0x4 0xe7 0x0 0x18 0x67 0x55
DEBUG:pymodbus.factory:Factory Response[4]
DEBUG:pymodbus.transaction:adding transaction 0
DEBUG:pymodbus.transaction:getting transaction 1
DEBUG:pymodbus.transaction:Running transaction 2
DEBUG:pymodbus.transaction:send: 0x1 0x4 0x31 0x10 0x0 0x1 0x3e 0xf3
DEBUG:pymodbus.transaction:recv: 0x1 0x4 0x2 0x7 0xda 0x3a 0x9b
DEBUG:pymodbus.factory:Factory Response[4]
DEBUG:pymodbus.transaction:adding transaction 0
DEBUG:pymodbus.transaction:getting transaction 2
293.15
```
 # code and logs here.
As you can see every second run of the script/program it "runs amuck" it just happens to be the first time in the above example.
```

**Comment by dhoomakethu** [comment]
@dmdelorme what kind of help are you seeking?

**Comment by dmdelorme** [comment]
woops i for got to include the info
it seems ever other time i run the code it has an issue connecting. see debug i included 2 debug outputs when i ran the code twice. 
pymodbus ver 1.3.2
OC Linux openplotter 4.9.13-v7+ #974 SMP Wed Mar 1 20:09:48 GMT 2017 armv7l GNU/Linux
On a RPi3
python version 2.7
the Modbus device is a epsolar tracer A
The Code
```
#import logging
#logging.basicConfig()
#log = logging.getLogger()
#log.setLevel(logging.DEBUG)
from pymodbus.client.sync import ModbusSerialClient as ModbusClient
#from pymodbus.mei_message import *
import socket
client = ModbusClient(method='rtu', port='/dev/ttyXRUSB0', baudrate=115200, stopbits = 1, bytesize = 8, timeout = 1)
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
client.connect()
#request = ReadDeviceInformationRequest(unit=1)
#response = client.execute(request)
#print repr(response.information)

result = client.read_input_registers(0x3100,10,unit=1)
pvVolts = float(result.registers[0] / 100.0)
pvAmps = float(result.registers[1] / 100.0)
batVolts = float(result.registers[4] / 100.0)
batchgAmps = float(result.registers[5] / 100.0)
ldVolts = float(result.registers[8] / 100.00)
ldAmps = float(result.registers[9] / 100.00)
ldnetAmps = batchgAmps-ldAmps
result2 = client.read_input_registers(0x3110,1,unit=1)
batTemp = float((result2.registers[0] / 100)+ 273.15)
#print 'send'
SignalK = '{"updates": [{"source": {"type": "CHARGER","src" : "epsolar"},"values":['
SignalK += '{"path": "electrical.chargers.tracer.batteries.main.voltage","value":'+str(round(batVolts, 2))+'}'
SignalK += ',{"path": "electrical.chargers.tracer.batteries.charge.current","value":'+str(batchgAmps)+'}'
SignalK += ',{"path": "electrical.chargers.tracer.pv.voltage","value":'+str(round(pvVolts,2))+'}'
SignalK += ',{"path": "electrical.chargers.tracer.pv.current","value":'+str(pvAmps)+'}'
SignalK += ',{"path": "electrical.chargers.tracer.load.voltage","value":'+str(ldVolts)+'}'
SignalK += ',{"path": "electrical.chargers.tracer.load.current","value":'+str(ldAmps)+'}'
SignalK += ',{"path": "electrical.chargers.tracer.loadnet.current","value":'+str(ldnetAmps)+'}'
SignalK += ',{"path": "electrical.chargers.tracer.batteries.temp","value":'+str(batTemp)+'}'
SignalK += ']}]}\n'
sock.sendto(SignalK, ('localhost', 55559))
#print pvVolts
#print pvAmps
#print result2.registers[0]/100
#print batteryAmps
print (batTemp)
client.close()
```
Debug output
```
DEBUG:pymodbus.transaction:Running transaction 1
DEBUG:pymodbus.transaction:send: 0x1 0x4 0x31 0x0 0x0 0xa 0x7e 0xf1
DEBUG:pymodbus.client.sync:will sleep to wait for 3.5 char
DEBUG:pymodbus.transaction:recv: 0x1 0x4 0x14 0x3 0x58 0x0 0x0
DEBUG:pymodbus.factory:Factory Response[1]
DEBUG:pymodbus.transaction:Transaction failed. (Modbus Error: [Invalid Message] ReadBitResponse(40)) 
DEBUG:pymodbus.transaction:send: 0x1 0x4 0x31 0x0 0x0 0xa 0x7e 0xf1
DEBUG:pymodbus.client.sync:will sleep to wait for 3.5 char
DEBUG:pymodbus.transaction:recv: 0x1 0x4 0x14 0x3 0x59 0x0 0x0 0x0 0x0 0x0 0x0 0x4 0xe8 0x0 0x0 0x0 0x0 0x0 0x0 0x4 0xe8 0x0 0x17 0x92 0x45
DEBUG:pymodbus.factory:Factory Response[1]
DEBUG:pymodbus.transaction:Transaction failed. (Modbus Error: [Invalid Message] ReadBitResponse(240)) 
DEBUG:pymodbus.transaction:send: 0x1 0x4 0x31 0x0 0x0 0xa 0x7e 0xf1
DEBUG:pymodbus.client.sync:will sleep to wait for 3.5 char
DEBUG:pymodbus.transaction:recv: 0x1 0x4 0x14 0x3 0x57 0x0 0x0 0x0 0x0 0x0 0x0 0x4 0xe8 0x0 0x0 0x0 0x0 0x0 0x0 0x4 0xe8 0x0 0x18 0xb8 0xa8
DEBUG:pymodbus.factory:Factory Response[1]
DEBUG:pymodbus.transaction:Transaction failed. (Modbus Error: [Invalid Message] ReadBitResponse(440)) 
DEBUG:pymodbus.transaction:getting transaction 1
Traceback (most recent call last):
  File "sktest.py", line 16, in <module>
    pvVolts = float(result.registers[0] / 100.0)
```
debug 2 working
```
DEBUG:pymodbus.transaction:Running transaction 1
DEBUG:pymodbus.transaction:send: 0x1 0x4 0x31 0x0 0x0 0xa 0x7e 0xf1
DEBUG:pymodbus.client.sync:will sleep to wait for 3.5 char
DEBUG:pymodbus.transaction:recv: 0x1 0x4 0x14 0x0 0x30 0x0 0x0 0x0 0x0 0x0 0x0 0x4 0xe2 0x0 0x0 0x0 0x0 0x0 0x0 0x4 0xe2 0x0 0x27 0x96 0x2d
DEBUG:pymodbus.factory:Factory Response[4]
DEBUG:pymodbus.transaction:adding transaction 0
DEBUG:pymodbus.transaction:getting transaction 1
DEBUG:pymodbus.transaction:Running transaction 2
DEBUG:pymodbus.transaction:send: 0x1 0x4 0x31 0x10 0x0 0x1 0x3e 0xf3
DEBUG:pymodbus.transaction:recv: 0x1 0x4 0x2 0x7 0xce 0x3a 0x94
DEBUG:pymodbus.factory:Factory Response[4]
DEBUG:pymodbus.transaction:adding transaction 0
DEBUG:pymodbus.transaction:getting transaction 2
292.15
```


Is there are some out standing issues with pymodbus or is my code bad. do i need to do more cleanup besides client.close()

**Comment by dhoomakethu** [comment]
You can start with lower baudrates(9600, 19200, 38400 etc) and increased read timeout . 
`client = ModbusClient(method='rtu', port='/dev/ttyXRUSB0', baudrate=115200, stopbits = 1, bytesize = 8, timeout = 1)
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)`

**Comment by dmdelorme** [comment]
tried that baud is non adjustable time out did not help nether. why every every second time?

**Comment by dhoomakethu** [comment]
You are receiving incomplete response and incorrect response in your failure case from the device. Is the wirings solid (correct termination installed, no loose connections ?) . Could you share the manual for the device , I could not find any on the net with the modbus specs for the device you have mentioned.

**Comment by dmdelorme** [comment]
Modbus Error: [Input/Output] Modbus Error: [Invalid Message] ReadBitResponse(432) i think it is incorrect?
I have tried different ports but no change.
https://github.com/kasbert/epsolar-tracer/blob/master/archive/1733_modbus_protocol.pdf

**Comment by dhoomakethu** [comment]
The Invalid Message error is raised when it is expecting a valid response but received a different one after decoding. I will run some manual decoding to see if something is wrong from the pymodbus side , but from the logs it looks like it is not. Let me double confirm.

**Comment by dmdelorme** [comment]
I might have a clue i am using a usb /rs485 cable it uses a exar driver.
`xr_usb_serial_common: Exar USB UART (serial port) driver`
I change to this version [https://www.exar.com/design-tools/software-drivers](url) 1.b connects but data is trash every time.
changed to [https://github.com/kasbert/epsolar-tracer](url)  	xr_usb_serial_common-1a
then every other read is garbage:) 100% improvement but works 50% of the time.
I also have a 10 amp Tracer and did the test with 1A same result.
I ordered a second cable and a wifi device.
the last resort is to run the program twice and take the good value. kinda like flipping a rigged coin. first toss 50/50 second toss 100% its dirty but it could work since the issue is so repeatable. 
I keep thinking that the stream is out of alignment and the error resets everything. byte alignment?
Is there a way i can connect to the device and just stream raw data out of it? I know $hit .....
did some more testing. got it read every time. when i just read 1 value? there are some blank/undocumented registers in the array could this be my problem?. also i have some issues with 0/100 when  volts/amps are 0... 

Thanks for your help?

**Comment by dhoomakethu** [comment]
@dmdelorme please refer #239, which is similar to what you are facing , the issues could be due to electro magnetic interference as well. Please check and revert

**Comment by dmdelorme** [comment]
I will look into that. I am not dealing with a lot of current  but have seen a few references to this issue. 
Thanks

**Comment by dmdelorme** [comment]
yup it looks like it was some loose wires causing noise. not 100% yet but better.
