### ISSUE TITLE
ModbusSerialClient throws AttributeError instead of returning False

### ISSUE THREAD

**Issue by stegm** [riptideio/pymodbus#377]
### Versions

* Python: 3.6
* OS: Ubuntu
* Pymodbus: 2.1
* Modbus Hardware (if used): None

### Pymodbus Specific
* Server: None
* Client: rtu - sync

### Description

If the `ModbusSerialClient` is created with method 'rtu' and a non-existing device, the `connect`-method throws an attribute error instead of returning `False`.

Example:

```python
>>> client = ModbusSerialClient(port='notexist', method='rtu')
>>> client.connect()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "lib/python3.6/site-packages/pymodbus/client/sync.py", line 476, in connect
    self.socket.interCharTimeout = self.inter_char_timeout
AttributeError: 'NoneType' object has no attribute 'interCharTimeout'
```

### Code and Logs

This is because of this code (`ModbusSerialClient.connect()`):
```python
            self.socket = serial.Serial(port=self.port, ...)
        except serial.SerialException as msg:
            _logger.error(msg)
            self.close()
        if self.method == "rtu":
            self.socket.interCharTimeout = self.inter_char_timeout
            self.last_frame_end = None
```
If the serial constructor fails, the exception is catched and close is called, which sets the `socket` field to `None`. Afterwards if the code access the `socket` field, an `AttributeError` is thrown.

**Comment by dhoomakethu** [comment]
There is sa fix available with v2.2.0rc1, please do `pip install pymodbus==2.2.0rc1` and update If that still does not solve the problem

**Comment by stegm** [comment]
2.2.0rc1 gives the same error for me.

```python
>>> import pymodbus
>>> pymodbus.__version__
'2.2.0.rc1'
>>> from pymodbus.client.sync import ModbusSerialClient
>>> client = ModbusSerialClient(port='notexist', method='rtu')
>>> client.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\temp\pvenv\lib\site-packages\pymodbus\client\sync.py", line 489, in connect
    self.socket.interCharTimeout = self.inter_char_timeout
AttributeError: 'NoneType' object has no attribute 'interCharTimeout'
```

**Comment by dhoomakethu** [comment]
Thanks for the confirmation. I will look in to this.

**Comment by dhoomakethu** [comment]
Please give a try with the latest on [pymodbus-2.2.0](https://github.com/riptideio/pymodbus/tree/pymodbus-2.2.0) branch and feedback. Thanks
