### ISSUE TITLE
Basic Tcp communication failure

### ISSUE THREAD

**Issue by bden16** [riptideio/pymodbus#672]
### Versions

* Python: 3.9
* OS: Windows
* Pymodbus: 2.5.2
* Modbus Hardware (if used): none

### Pymodbus Specific
* Server: **tcp**/rtu/ascii - sync/async 
* Client: **tcp**/rtu/ascii - sync/async

### Description

Hi,

I try to set up the simplest connexion between two python scripts in Modbus, I'm learning in an internship for engineering studies. I tried various things, the first one with a modbus "context", the second one without it. I don't understand what's wrong, could someone help me with my issue and maybe explain a bit simplier how modbus connexions work.

### Code and Logs
#The server code with context :

from pymodbus.server.sync import StartTcpServer
from pymodbus.datastore import ModbusSparseDataBlock

def run_server():

    data = ModbusSparseDataBlock({0x00:3, 0x01:5, 0x02:7})
    StartTcpServer(context=data, address=("127.0.0.1", 502))

run_server()   

#The server code without context :

from pymodbus.server.sync import StartTcpServer
from pymodbus.datastore import ModbusSparseDataBlock

def run_server():
    StartTcpServer(context=data, address=("127.0.0.1", 502))

run_server()   

#The client code :

from pymodbus.client.sync import ModbusTcpClient as ModbusClient
    
UNIT= 0x01

def run_client():
    
    print("DĂ©marrage")
    client = ModbusClient('127.0.0.1', 502)
    client.connect()
    client.write_coils(1, (True, False), unit=UNIT) 
    collected = client.read_coils(1, count=2, unit = UNIT)
    
    if not collected.isError():
        print(collected.coils)
    else:
        print("Erreur de communication")
        print(collected)
    client.close()

run_client()       
    
#The client logs with the context :

Démarrage
Traceback (most recent call last):
  File "C:\Users\Denis\Desktop\Stage\Ecoptine\Python\Client Tcp.py", line 20, in <module>
    run_client()
  File "C:\Users\Denis\Desktop\Stage\Ecoptine\Python\Client Tcp.py", line 10, in run_client
    client.write_coils(1, (True, False), unit=UNIT)
  File "C:\Python39\lib\site-packages\pymodbus\client\common.py", line 81, in write_coils
    return self.execute(request)
  File "C:\Python39\lib\site-packages\pymodbus\client\sync.py", line 109, in execute
    return self.transaction.execute(request)
  File "C:\Python39\lib\site-packages\pymodbus\transaction.py", line 174, in execute
    response, last_exception = self._transact(
  File "C:\Python39\lib\site-packages\pymodbus\transaction.py", line 293, in _transact
    result = self._recv(response_length, full)
  File "C:\Python39\lib\site-packages\pymodbus\transaction.py", line 325, in _recv
    read_min = self.client.framer.recvPacket(min_size)
  File "C:\Python39\lib\site-packages\pymodbus\framer\__init__.py", line 49, in recvPacket
    return self.client.recv(size)
  File "C:\Python39\lib\site-packages\pymodbus\client\sync.py", line 89, in recv
    return self._recv(size)
  File "C:\Python39\lib\site-packages\pymodbus\client\sync.py", line 298, in _recv
    return self._handle_abrupt_socket_close(
  File "C:\Python39\lib\site-packages\pymodbus\client\sync.py", line 343, in _handle_abrupt_socket_close
    raise ConnectionException(msg)
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] ModbusTcpClient(127.0.0.1:502): Connection unexpectedly closed 0.000000 seconds into read of 8 bytes without response from unit before it closed connection

Démarrage
Erreur de communication

#The client logs without it :

Démarrage
Erreur de communication
Exception Response(129, 1, SlaveFailure)

```
Thanks a lot in advance

**Comment by dhoomakethu** [comment]
Can you try with elevated permissions for port 502 or use other ports>1024 and see if the issue still persists?
