### ISSUE TITLE
updating_server.py example results in "TypeError: 'ModbusSlaveContext' object is not subscriptable"

### ISSUE THREAD

**Issue by robot-ranger** [riptideio/pymodbus#710]
### Versions

* Python: 3.10
* OS: W10
* Pymodbus: 2.5.3
* Modbus Hardware (if used): trying to run a server. developing on windows, planning on raspi

### Pymodbus Specific
* Server: tcp, synchronous

### Description
I am sure this is something really stupid and obvious. I am not an expert.

I am trying to get a server running, but I cant figure out how to ~~write to the discrete inputs~~ update the context for the purposes of updating digital inputs. Im trying to run the updating_server.py example but with a synchronous setup instead of async. I have removed the looping call and replaced with a thread per the comments in the file, but I get the following:
"TypeError: 'ModbusSlaveContext' object is not subscriptable".

> Exception in thread Thread-1 (updating_writer):
Traceback (most recent call last):
  File "C:\Users\tedw\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\tedw\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run    self._target(*self._args, **self._kwargs)
  File "C:\Users\tedw\Documents\Sandbox\garbage\pymodbus_test.py", line 54, in updating_writer   
    values = context[slave_id].getValues(register, address, count=5)
TypeError: 'ModbusSlaveContext' object is not subscriptable

below is how my code looks now, with my attempts to modify updating_server.py for synchronous:

### Code and Logs

```python
"""
Pymodbus Server With Updating Thread
--------------------------------------------------------------------------
This is an example of having a background thread updating the
context while the server is operating. This can also be done with
a python thread::
	from threading import Thread
	thread = Thread(target=updating_writer, args=(context,))
	thread.start()
"""
# --------------------------------------------------------------------------- #
# import the modbus libraries we need
# --------------------------------------------------------------------------- #
from threading import Thread
from time import sleep
from pymodbus.version import version
from pymodbus.server.sync import StartTcpServer
#from pymodbus.server.asynchronous import StartTcpServer
from pymodbus.device import ModbusDeviceIdentification
from pymodbus.datastore import ModbusSequentialDataBlock
from pymodbus.datastore import ModbusSlaveContext, ModbusServerContext
from pymodbus.transaction import ModbusRtuFramer, ModbusAsciiFramer

# --------------------------------------------------------------------------- #
# import the twisted libraries we need
# --------------------------------------------------------------------------- #
#from twisted.internet.task import LoopingCall

# --------------------------------------------------------------------------- #
# configure the service logging
# --------------------------------------------------------------------------- #
import logging
logging.basicConfig()
log = logging.getLogger()
log.setLevel(logging.DEBUG)

# --------------------------------------------------------------------------- #
# define your callback process
# --------------------------------------------------------------------------- #


def updating_writer(a):
	""" A worker process that runs every so often and
	updates live values of the context. It should be noted
	that there is a race condition for the update.
	:param arguments: The input arguments to the call
	"""
	
	log.debug("updating the context")
	sleep(2)
	context = a[0]
	register = 3
	slave_id = 0x00
	address = 0x10
	values = context[slave_id].getValues(register, address, count=5)
	values = [v + 1 for v in values]
	log.debug("new values: " + str(values))
	context[slave_id].setValues(register, address, values)


def run_updating_server(ip, port):
	# ----------------------------------------------------------------------- # 
	# initialize your data store
	# ----------------------------------------------------------------------- # 
	
	store = ModbusSlaveContext(
		di=ModbusSequentialDataBlock(0, [17]*100),
		co=ModbusSequentialDataBlock(0, [17]*100),
		hr=ModbusSequentialDataBlock(0, [17]*100),
		ir=ModbusSequentialDataBlock(0, [17]*100))
	context = ModbusServerContext(slaves=store, single=True)
	
	# ----------------------------------------------------------------------- # 
	# initialize the server information
	# ----------------------------------------------------------------------- # 
	identity = ModbusDeviceIdentification()
	identity.VendorName = 'pymodbus'
	identity.ProductCode = 'PM'
	identity.VendorUrl = 'http://github.com/riptideio/pymodbus/'
	identity.ProductName = 'pymodbus Server'
	identity.ModelName = 'pymodbus Server'
	identity.MajorMinorRevision = version.short()
	
	# ----------------------------------------------------------------------- # 
	# run the server you want
	# ----------------------------------------------------------------------- # 
	# time = 5  # 5 seconds delay
	# loop = LoopingCall(f=updating_writer, a=(context,))
	# loop.start(time, now=False) # initially delay by time
	thread = Thread(target=updating_writer, args=(context,))
	thread.start()
	print('Starting server at ' + ip + ' on port ' + str(port))
	StartTcpServer(context, identity=identity, address=(ip, port))


if __name__ == "__main__":
	run_updating_server('127.0.0.1', 5020)

```

**Comment by dhoomakethu** [comment]
Use `context = a` instead of `context = a[0]` .
