### ISSUE TITLE
AttributeError: 'ModbusDisconnectedRequestHandler' object has no attribute 'protocol' when closing UDP server

### ISSUE THREAD

**Issue by maltekliemann** [riptideio/pymodbus#711]
### Versions

* Python: 3.9.7
* OS: macOS Monterey 12.1
* Pymodbus: 2.5.3 (dev)
* Modbus Hardware (if used): None

### Pymodbus Specific

* Server: asyncio UDP

### Description

I'm trying to open and then gracefully close an asyncio UDP server.

### Code and Logs

```python
import asyncio

from pymodbus.server.async_io import StartUdpServer
from pymodbus.datastore import ModbusSequentialDataBlock
from pymodbus.datastore import ModbusSlaveContext, ModbusServerContext

async def main():
    modbus_slave_context = ModbusSlaveContext(
        di=ModbusSequentialDataBlock(0, [17] * 100),
        co=ModbusSequentialDataBlock(0, [17] * 100),
        hr=ModbusSequentialDataBlock(0, [17] * 100),
        ir=ModbusSequentialDataBlock(0, [17] * 100),
    )
    modbus_server = await StartUdpServer(
        modbus_server_context, address=("0.0.0.0", 5021), defer_start=True
    )
    task = asyncio.create_task(modbus_server.serve_forever())
    await asyncio.sleep(1)
    modbus_server.server_close()
    await task

if __name__ == "__main__":
    asyncio.run(main())
```

This results in:

```python
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:pymodbus.server.async_io:Socket [0.0.0.0:5021] opened
ERROR:pymodbus.server.async_io:Datastore unable to fulfill request: 'ModbusDisconnectedRequestHandler' object has no attribute 'protocol'; Traceback (most recent call last):
  File "/Users/malte/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymodbus/server/async_io.py", line 109, in connection_lost
    self._log_exception()
  File "/Users/malte/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pymodbus/server/async_io.py", line 61, in _log_exception
    sock_name = self.protocol._sock.getsockname()
AttributeError: 'ModbusDisconnectedRequestHandler' object has no attribute 'protocol'
```

**Comment by janiversen** [comment]
This is solved on del
```
            if hasattr(self, "protocol"):
                sock_name = (
                    self.protocol._sock.getsockname()  # pylint: disable=protected-access
                )
```
