### ISSUE TITLE
AttributeError when using uvloop

### ISSUE THREAD

**Issue by tomas-bozek** [riptideio/pymodbus#778]
Linux: Ubuntu 20.04
Python: 3.8
Pymodbus: 2.5.3

Exception when using `uvloop`

```
2022-04-13 13:16:13,035 ERROR    pymodbus.server.async_io Datastore unable to fulfill request: 'uvloop.loop.UDPTransport' object has no attribute '_sock'; Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pymodbus/server/async_io.py", line 109, in connection_lost
    self._log_exception()
  File "/usr/local/lib/python3.8/dist-packages/pymodbus/server/async_io.py", line 61, in _log_exception
    sock_name = self.protocol._sock.getsockname()
AttributeError: 'uvloop.loop.UDPTransport' object has no attribute '_sock'
```

**Comment by dhoomakethu** [comment]
`uvloop` is not supported , use `asyncio` loop instead.

**Comment by tracernz** [comment]
Can <BaseTransport>.get_extra_info('socket') not be used instead of accessing the private _sock member? It appears to only be used to get the socket name.

https://docs.python.org/3/library/asyncio-protocol.html#asyncio.BaseTransport.get_extra_info

**Comment by janiversen** [comment]
try it, patches are welcome.

**Comment by janiversen** [comment]
Closing as non-supported.
